# Code of Conduct {-#coc}

A Code of Conduct is useful to define accepted and acceptable behaviors and to promote high standards of professional practice. It also provides a benchmark for self-evaluation and acts as a vehicle for better identity of the community and organization.

This code (CoC) applies to any participant at the R Conference – developers, participants in meetings, teleconferences, mailing lists, conferences or functions, etc. Note that this code augments rather than replaces legal rights and obligations pertaining to any particular situation.

## Workshops attendees {-}

Part 1. Introduction

We are committed to creating a friendly and respectful place for learning, teaching and contributing.
All participants in our events and communications are expected to show respect and courtesy to others.

To make clear what is expected, everyone participating is required to conform to the Code of Conduct.
This Code of Conduct applies to all spaces including, but not limited to,
workshops, email lists, and online forums such as GitHub, Slack and Twitter.
Workshop hosts are expected to assist with the enforcement of the Code of Conduct.

Workshop hosts are responsible for enforcing the Code of Conduct.
It can be contacted by emailing chend@vt.edu and/or ambrown7@vt.edu.
All reports will be reviewed and will be kept confidential.

Part 2. Code of Conduct

We are dedicated to providing a welcoming and supportive environment for all people, regardless of background or identity.
As such, we do not tolerate behaviour that is disrespectful to our teachers or learners or that excludes, intimidates, or causes discomfort to others.
We do not tolerate discrimination or harassment based on characteristics that include, but are not limited to,
gender identity and expression, sexual orientation, disability, physical appearance, body size, citizenship, nationality, ethnic or social origin, pregnancy, familial status, veteran status, genetic information, religion or belief (or lack thereof), membership of a national minority, property, age, education, socio-economic status, technical choices, and experience level.

Everyone who participates in workshop activities is required to conform to this Code of Conduct.
It applies to all spaces including, but not limited to, workshops, email lists, and online forums such as GitHub, Slack and Twitter.
Workshop hosts are expected to assist with the enforcement of the Code of Conduct.
By participating, participants indicate their acceptance of the procedures resolves any Code of Conduct incidents, which may include storage and processing of their personal information.

Part 2.1 Expected behaviour

All participants in our events and communications are expected to show respect and courtesy to others.
All interactions should be professional regardless of platform: either online or in-person.
In order to foster a positive and professional learning environment we encourage the following kinds of behaviours in all events and platforms:

- Use welcoming and inclusive language
- Be respectful of different viewpoints and experiences
- Gracefully accept constructive criticism
- Focus on what is best for the community
- Show courtesy and respect towards other community members

Note: See the
[four social rules](https://www.recurse.com/manual#sub-sec-social-rules)
for further recommendations.

Part 2.2 Unacceptable behaviour

Examples of unacceptable behaviour by participants at any event/platform include:

- written or verbal comments which have the effect of excluding people on the basis of membership of any specific group
- causing someone to fear for their safety, such as through stalking, following, or intimidation
- violent threats or language directed against another person
- the display of sexual or violent images
- unwelcome sexual attention
- nonconsensual or unwelcome physical contact
- sustained disruption of talks, events or communications
- insults or put downs
- sexist, racist, homophobic, transphobic, ableist, or exclusionary jokes
- excessive swearing
- incitement to violence, suicide, or self-harm
- continuing to initiate interaction (including photography or recording) with someone after being asked to stop
- publication of private communication without consent

Part 2.3 Consequences of Unacceptable behaviour

Participants who are asked to stop any inappropriate behaviour are expected to comply immediately.
This applies to any event and platform, either online or in-person.
If a participant engages in behaviour that violates this code of conduct,
the organisers may warn the offender, ask them to leave the event or platform (without refund),
or engage the organizers to investigate the Code of Conduct violation and impose appropriate sanctions.


Example CoC from the Carpentries:

https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html



### About this Document {-}

This document is adapted from guidelines written by The Carpentries, which was adapted from guidelines written by the Django Project, which was itself based on the Ada Initiative template and the PyCon 2013 Procedure for Handling Harassment Incidents. Contributors to the the initial document are Adam Obeng, Aleksandra Pawlik, Bill Mills, Carol Willing, Erin Becker, Hilmar Lapp, Kara Woo, Karin Lagesen, Pauline Barmby, Sheila Miguez, Simon Waldman, and Tracy Teal. Additional language was added by Otter Tech from the PyCon U.S. 2018 Code of Conduct (licensed CC BY 3.0) In 2018, the Code of Conduct was revised to add a summary, straightforward examples of both beneficial and unwanted behaviors, and evaluating intent. Reporting guidelines were also revised to include alternate contact points and a reporting form with the procedure was added. In 2019, an appeal process, the procedure for following up with a reportee, terminology, CoC incident response procedure, termed suspension checklist, expanded clauses for conflicts of interest, and committee membership agreement were included. Contributors of these revised documents are Ethan White, Kari L. Jordan, Karin Lagesen, Malvika Sharan, Samantha Ahern, and Simon Waldman.
