---
output: html_document
editor_options: 
  chunk_output_type: console
---
# Descriptive Calculations

## Introduction {#descriptives-intro}

## Learning Objectives {#descriptives-lo}

## Building the pipeline

New script, clear your environment, re-load your libraries

::::: {.rBlock}
###### R {-}
```{r, results='hide'}
library(tidyverse)
```

```{r}
tumor_subset <- read_csv("data/tumor_filtered.csv")
```

```{r}
tumor_subset
```
:::::

::::: {.pyBlock}
###### Python {-}
```{python}
import pandas as pd

tumor_subset = pd.read_csv("data/tumor_filtered.csv")
tumor_subset
```
:::::

## Summary statistics

::::: {.rBlock}
###### R {-}
```{r}
tumor_subset %>%
  filter(Day == 0) %>%
  pull(Size)
```

```{r}
tumor_subset %>%
  filter(Day == 0) %>%
  pull(Size) %>%
  mean()
  
```
:::::

::::: {.pyBlock}
###### Python {-}
```{python}
tumor_subset.loc[tumor_subset["Day"] == 0, "Size"]
```

```{python}
tumor_subset.loc[tumor_subset["Day"] == 0, "Size"].mean()
```

```{python}
(tumor_subset
  .loc[tumor_subset["Day"] == 0, "Size"]
  .mean()
)
```
:::::

::::: {.rBlock}
###### R {-}

```{r}
tumor_subset %>%
  filter(Group == 1, Day == 0) %>%
  pull(Size) %>%
  mean()
```

```{r}
tumor_subset %>%
  filter(Group == 2, Day == 0) %>%
  pull(Size) %>%
  mean()
```

```{r}
tumor_subset %>%
  filter(Group == 3, Day == 0) %>%
  pull(Size) %>%
  mean()
```

```{r}
tumor_subset %>%
  filter(Group == 4, Day == 0) %>%
  pull(Size) %>%
  mean()
```

```{r}
tumor_subset %>%
  pull(Group) %>%
  unique()
```
:::::

::::: {.pyBlock}
###### Python {-}
```{python}
(tumor_subset
  .loc[tumor_subset["Group"] == 1, "Size"]
  .mean()
)
```

```{python}
(tumor_subset
  .loc[tumor_subset["Group"] == 2, "Size"]
  .mean()
)
```

```{python}
(tumor_subset
  .loc[tumor_subset["Group"] == 3, "Size"]
  .mean()
)
```

```{python}
(tumor_subset
  .loc[tumor_subset["Group"] == 4, "Size"]
  .mean()
)
```

```{python}
(tumor_subset
  .loc[:, "Group"]
  .unique()
)
```
:::::

## Groupby operations

::::: {.rBlock}
###### R {-}
```{r}
tumor_subset %>%
  filter(Day == 0) %>%
  group_by(Group) %>%
  summarize(avg_size = mean(Size))
  
```
:::::

::::: {.pyBlock}
###### Python {-}
```{python}
(tumor_subset
  .loc[tumor_subset["Day"] == 0]
  .groupby("Group")
  .mean()
)
```

```{python}
(tumor_subset
  .loc[tumor_subset["Day"] == 0]
  .groupby("Group")
  ["Size"]
  .mean()
)
```

```{python}
import numpy as np

(tumor_subset
  .loc[tumor_subset["Day"] == 0]
  .groupby("Group")
  ["Size"]
  .agg(avg_size = np.mean)
)
```

```{python}
(tumor_subset
  .loc[tumor_subset["Day"] == 0]
  .groupby("Group")
  .agg(avg_size = ("Size", np.mean))
)
```
:::::

::::: {.rBlock}
###### R {-}
```{r}
tumor_subset %>%
  group_by(Group, Day) %>%
  summarize(avg_size = mean(Size),
            sd_size = sd(Size),
            q1 = quantile(Size, probs = .25)
            )
```
:::::

::::: {.pyBlock}
###### Python {-}
```{python}
(tumor_subset
  .groupby(["Group", "Day"])
  .agg(avg_size = ("Size", np.mean),
       std_size = ("Size", np.std),
       q25_size = ("Size", lambda x: np.quantile(x, q=.25)))
)
```

```{python}
(tumor_subset
  .groupby(["Group", "Day"])
  .agg(avg_size = ("Size", np.mean),
       std_size = ("Size", np.std),
       q25_size = ("Size", lambda x: np.quantile(x, q=.25)))
  .reset_index()
)
```
:::::

## Summary {#descriptives-summary}

## Additional Resources {#descriptives-resources}
